import Head from 'next/head'

export default function Home() {
    return (
        <>
            <Head>
                <title>DragonVale Quest Matcher - The DragonVale Lair</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
            </Head>
            <main className="main">
                <section className="card">
                    <h1 className="card__title">Quest Matcher</h1>
                    <p>Under constrution...</p>
                    <img
                        className="building"
                        src="/building.webp"
                    />
                </section>
            </main>
        </>
    )
}
