const waitingTexts = [
    'Hatching dragon eggs...',
    'Counting dragon eggs...',
    'Calculating 9 + 10...',
    'Preparing guess...',
    'Speeding up the process with gems...',
    'Preparing romantic dinner...',
    'Checking habitat space...',
    'Organizing dragon races...',
    'Exploring the Breeding Cave...',
    'Breeding in progress...',
    'Consulting Gaia...',
    'Asking Kairos to speed things up...',
    'Praising Quil for The DragonVale Compendium...',
    'Check out the DragonVale Reddit community.',
    'Check out the DragonVale Community Forum.',
    'Using data from The DragonVale Compendium.',
    'Have you tried The DragonVale Sandbox?',
    "The Blue Fire Dragon's breath is hotter!",
    'Is it safe to hug the cute Blazing Dragon?',
    'Checking for limited dragons...',
    'Who let the dargons out?',
    'Sorry, I got distracted by Name That Egg.',
    'TODO: Write something funny before release.',
]
export default waitingTexts
