const waitingTexts = [
    'Hatching dragon eggs...',
    'Counting dragon eggs...',
    'Calculating 9 + 10...',
    'Preparing guess...',
    'Speeding up the process with gems...',
    'Preparing romantic dinner...',
    'Checking habitat space...',
    'Organizing dragon races...',
    'Exploring the Breeding Cave...',
    'Breeding in progress...',
    'Consulting Gaia...',
    'Asking Kairos to speed things up...',
    'Praising Quil for The DragonVale Compendium...',
    'Check out the DragonVale Reddit community.',
    'Check out the DragonVale Community Forum.',
    'Using data from The DragonVale Compendium.',
    'Have you tried The DragonVale Sandbox?',
    "The Blue Fire Dragon's breath is hotter!",
    'Is it safe to hug the cute Blazing Dragon?',
    'The Pollen Dragon turned me into a frog!',
    'Sorry, I got distracted by Name That Egg.',
    'TODO: Write something funny before release.',
    'Can i eat the Gingerbread Dragon yet?',
    'Waiting for holidays...',
    'Presents are great, but Gift Dragons are better.',
    'The Dargon Dragon might appear unexpectedly...',
    'Working on new features...',
    'Looking for improvement suggestions...',
]
export default waitingTexts
