// dragonsWithImages.ts

export const dragonsWithImages: string[] = [
    'abraxas',
    'abyss',
    'acid',
    'air',
    'air rift',
    'alpenglow',
    'antumbra',
    'aperture',
    'apocalypse',
    // "arid",
    'ash',
    'auroch',
    // 'bahamut',
    'blazing',
    'blightwing',
    'bonescale',
    'bouldershock',
    'bramble',
    'brass',
    'brilliant',
    'cactus',
    'cave',
    'celerulean',
    'char',
    'chimneypuff',
    'chitin',
    'chromacorn',
    'chrome',
    'cold',
    'cold rift',
    'coldforge',
    'conch',
    'copper',
    'corrupticorn',
    'crypt',
    'crystal',
    'current',
    'cyclone',
    'dapplethorn',
    'dark',
    'dark rift',
    'darkling',
    // 'daylily',
    'dazzle',
    'drifter',
    'dungeon',
    'earth',
    'earth rift',
    'etch',
    'exterrean',
    'fire',
    'fire rift',
    'firefly',
    'fissure',
    'flash',
    'flower',
    'forge',
    'frostbite',
    'frostfire',
    'frostfluff',
    'fulgurite',
    'fungus',
    // 'gaia',
    'gamma',
    'ghast',
    'hail',
    'howl',
    'hydnellum',
    'ignite',
    'iron',
    'ironwood',
    'ivy',
    // 'kairos',
    'kampos',
    'lacuna',
    'lava',
    'light',
    'light rift',
    'lightning',
    'lightning rift',
    'lodestone',
    'magnetic',
    'malachite',
    'metal',
    'metal rift',
    'meteor',
    'miasma',
    'mine',
    'mirage',
    'mirror',
    'molten',
    'nightbloom',
    'nightshade',
    'nimbus',
    'nox',
    'ooze',
    'pearlescent',
    'pepper',
    'plant',
    'plant rift',
    'plasma',
    'plumewing',
    'promethium',
    'quake',
    'quicksilver',
    'radiant',
    'ragnarok',
    'rayleian',
    'razortail',
    'rigel',
    'root',
    // 'ruckus',
    'ruin',
    'rust',
    'sandscale',
    'scorch',
    'scoria',
    'shining',
    'shockproof',
    'silverline',
    'snapper',
    'snowsquall',
    // 'snowy silver',
    'sonic',
    'spark',
    'spectrapod',
    'spore',
    'steel',
    'storm',
    'subterranean',
    'sulfur',
    'surge',
    'teidian',
    'tempest',
    'thistle',
    'thorn',
    'thrasher',
    'thunder',
    'thunderbird',
    // 'tiamat',
    'trench',
    // 'tsaishen',
    'tumblethorn',
    'vaul',
    'verdigris',
    'viridian',
    'void',
    'voltaic',
    'watch',
    'water',
    'water rift',
    'wavelyte',
    'wisp',
    'wraith',
    'xanthium',
    'yolkwing',
    'zaffer',
]
